### ISSUE TITLE
External access has strange behaviour

### ISSUE THREAD

**Issue by Yothri** [blackdesert/DesertProject#1]
Hi,

maybe you (karyzir) remember me, i also worked on a BDO server emulator some time ago at korean cbt3. 

Well i tried your files they are working great. Great work, but i got a small issue when i try accessing from over the network.

In loginserver and world server cfg i set ip to 0.0.0.0 to make it possible to connect from outside.
In the region packet from loginserver to client i changed the world server ip to my hamachi ip (where my friend is also connected to).

Connection works when clicking on start, but it loads forever. I am sure it can connect, because i let my friend call my hamachi ip :8888 in browser. It loads forever but when canceling the reqeust in login server there is some log ofc. Means the connection works, but server or client expects/sends other packets. Could you have a look at it ? Basically just to make it possible to let other pc´s connect to the server.

Thanks and great work.

**Comment by blackdesert** [comment]
AI is not done. Closed.

**Comment by karyzir42** [comment]
Yep, now im working on characters synchronisation(spawn, movement, skill action, and other visible action`s) need time for analyse all packet`s for this part.

**Comment by Yothri** [comment]
Nah, you guys misunderstood me. External access does not work not even on loginseerver.

**Comment by blackdesert** [comment]
So what ? We just told you that you wont be able to play with him even if you wanted to

**Comment by Yothri** [comment]
I know, i can read the source. There are no packets for handling multiple clients atm. But the login for every player should be the same and should work for everyone the same. Local players can connect, external connectors too, but can't pass the login screen. it says now processing forever and login server says unknown packet received.

**Comment by blackdesert** [comment]
Means you have wrong client

**Comment by Yothri** [comment]
I tested this already, both blackdesert32.exe (mine and the one of my friend) habe the same checksum. Also we are using the client from European cbt1 with latest patches.

**Comment by blackdesert** [comment]
1 exe checksum is not enough.

**Comment by Yothri** [comment]
Ok, i will inspect both clients to be the same, if not i will make them the same and then i will post the result here.
