### ISSUE TITLE
give pliz sql.

### ISSUE THREAD

**Issue by Karma1** [blackdesert/DesertProject#2]
give pliz sql.

**Comment by Brandelis** [comment]
The database is automatically created once the servers start. The latest cryptography has changed so the servers won't work until new crypto is implemented

**Comment by Karma1** [comment]
I need a database that I want to work skills at all possible?

**Comment by Karma1** [comment]
[URL=http://fastpic.ru/][IMG]http://i77.fastpic.ru/big/2016/0603/14/7d0774fb9eb88d953281617df5471b14.png[/IMG][/URL]

**Comment by Karma1** [comment]
http://i77.fastpic.ru/big/2016/0603/14/7d0774fb9eb88d953281617df5471b14.png

**Comment by Karma1** [comment]
I need a database that I want to work skills at all possible?  http://fastpic.ru/view/77/2016/0603/7d0774fb9eb88d953281617df5471b14.png.html  


>Пятница,  3 июня 2016, 0:20 +03:00 от Obey <notifications@github.com>:
>
>The database is automatically created once the servers start. The latest cryptography has changed so the servers won't work until new crypto is implemented 
>
>
>

**Comment by Brandelis** [comment]
I will send you the exported database when I get home from work

**Comment by Karma1** [comment]
Thank you very much.

**Comment by Karma1** [comment]
maybe I could help you with the Black Desert online

**Comment by Brandelis** [comment]
https://mega.nz/#!ZQkQ2aJJ

https://mega.nz/#!0MUi3DzI
